###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

disable_analytics: true
_site_root: /katrinkerber/
