###########################################################################################
#
#  DEV ENVIRONMENT VARIABLES
#
###########################################################################################

disable_analytics: true