###########################################################################################
#
#  STATAMIC CUSTOM ROUTES
#
###########################################################################################

# SIMPLE ROUTE EXAMPLE
# Visiting example.com/success will...
# load the /templates/success.html template

# /success : success


# ADVANCED ROUTE EXAMPLE
# Visiting example.com/members/login will...
# load the /templates/success.html template
# and use the /layouts/system.html layout

# /members/login
#   template: success
#   layout: system